with-expecter: True
inpackage: True
dir: mocks/{{ replaceAll .InterfaceDirRelative "internal" "internal_" }}
mockname: "{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
filename: "{{.InterfaceName}}.go"
all: True
packages:
  energy-response-assignment/app/service:
    config:
      recursive: True
  energy-response-assignment/app/repository:
    config:
      recursive: True
  energy-response-assignment/util/mailer:
    config:
      recursive: True