// Code generated by mockery v2.42.3. DO NOT EDIT.

package service

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Newsletter is an autogenerated mock type for the Newsletter type
type Newsletter struct {
	mock.Mock
}

type Newsletter_Expecter struct {
	mock *mock.Mock
}

func (_m *Newsletter) EXPECT() *Newsletter_Expecter {
	return &Newsletter_Expecter{mock: &_m.Mock}
}

// SendNewsLetter provides a mock function with given fields: ctx, header, body
func (_m *Newsletter) SendNewsLetter(ctx context.Context, header string, body string) error {
	ret := _m.Called(ctx, header, body)

	if len(ret) == 0 {
		panic("no return value specified for SendNewsLetter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, header, body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Newsletter_SendNewsLetter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendNewsLetter'
type Newsletter_SendNewsLetter_Call struct {
	*mock.Call
}

// SendNewsLetter is a helper method to define mock.On call
//   - ctx context.Context
//   - header string
//   - body string
func (_e *Newsletter_Expecter) SendNewsLetter(ctx interface{}, header interface{}, body interface{}) *Newsletter_SendNewsLetter_Call {
	return &Newsletter_SendNewsLetter_Call{Call: _e.mock.On("SendNewsLetter", ctx, header, body)}
}

func (_c *Newsletter_SendNewsLetter_Call) Run(run func(ctx context.Context, header string, body string)) *Newsletter_SendNewsLetter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Newsletter_SendNewsLetter_Call) Return(_a0 error) *Newsletter_SendNewsLetter_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Newsletter_SendNewsLetter_Call) RunAndReturn(run func(context.Context, string, string) error) *Newsletter_SendNewsLetter_Call {
	_c.Call.Return(run)
	return _c
}

// NewNewsletter creates a new instance of Newsletter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNewsletter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Newsletter {
	mock := &Newsletter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
