// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"context"
)

type Querier interface {
	BatchUpdateSendingEmailsStatus(ctx context.Context, arg []BatchUpdateSendingEmailsStatusParams) *BatchUpdateSendingEmailsStatusBatchResults
	CountActiveSubscriber(ctx context.Context) (int64, error)
	// description: Create a new newsletter
	// input: header: String, body: String
	// output: Newsletter: Object
	// example: CreateNewsLetter("Newsletter 1", "This is the first newsletter")
	CreateNewsLetter(ctx context.Context, arg CreateNewsLetterParams) (Newsletter, error)
	CreateSendingEmails(ctx context.Context, arg []CreateSendingEmailsParams) *CreateSendingEmailsBatchResults
	GetActiveSubscribersWithPaginate(ctx context.Context, arg GetActiveSubscribersWithPaginateParams) ([]Subscriber, error)
	GetSubscriber(ctx context.Context, email string) (Subscriber, error)
	UpdateSendingEmailsStatus(ctx context.Context, arg UpdateSendingEmailsStatusParams) (SendingEmail, error)
	UpsertSubscriber(ctx context.Context, arg UpsertSubscriberParams) (Subscriber, error)
}

var _ Querier = (*Queries)(nil)
