// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: sendEmail.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const updateSendingEmailsStatus = `-- name: UpdateSendingEmailsStatus :one
UPDATE sending_emails
SET status     = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, subscriber_id, newsletter_id, status, created_at, updated_at
`

type UpdateSendingEmailsStatusParams struct {
	ID     uuid.UUID
	Status Status
}

func (q *Queries) UpdateSendingEmailsStatus(ctx context.Context, arg UpdateSendingEmailsStatusParams) (SendingEmail, error) {
	row := q.db.QueryRow(ctx, updateSendingEmailsStatus, arg.ID, arg.Status)
	var i SendingEmail
	err := row.Scan(
		&i.ID,
		&i.SubscriberID,
		&i.NewsletterID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
