// Code generated by mockery v2.42.3. DO NOT EDIT.

package mailer

import mock "github.com/stretchr/testify/mock"

// Mailer is an autogenerated mock type for the Mailer type
type Mailer struct {
	mock.Mock
}

type Mailer_Expecter struct {
	mock *mock.Mock
}

func (_m *Mailer) EXPECT() *Mailer_Expecter {
	return &Mailer_Expecter{mock: &_m.Mock}
}

// SendMail provides a mock function with given fields: to, subject, body
func (_m *Mailer) SendMail(to []string, subject string, body string) error {
	ret := _m.Called(to, subject, body)

	if len(ret) == 0 {
		panic("no return value specified for SendMail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]string, string, string) error); ok {
		r0 = rf(to, subject, body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Mailer_SendMail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMail'
type Mailer_SendMail_Call struct {
	*mock.Call
}

// SendMail is a helper method to define mock.On call
//   - to []string
//   - subject string
//   - body string
func (_e *Mailer_Expecter) SendMail(to interface{}, subject interface{}, body interface{}) *Mailer_SendMail_Call {
	return &Mailer_SendMail_Call{Call: _e.mock.On("SendMail", to, subject, body)}
}

func (_c *Mailer_SendMail_Call) Run(run func(to []string, subject string, body string)) *Mailer_SendMail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]string), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *Mailer_SendMail_Call) Return(_a0 error) *Mailer_SendMail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Mailer_SendMail_Call) RunAndReturn(run func([]string, string, string) error) *Mailer_SendMail_Call {
	_c.Call.Return(run)
	return _c
}

// NewMailer creates a new instance of Mailer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMailer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mailer {
	mock := &Mailer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
